name: Makefile CI

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get -y install libgit2-dev

    - name: Compile
      run: make

    - name: Test
      run: bash ./run-tests.sh
      shell: bash
